# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "superagent"
primary_region = "sjc"

[build]

[env]
  NODE_ENV = "production"

[processes]
  app = "npm start"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
